// Generated by Haxe 5.0.0-alpha.1+1423a5f
(function ($global) { "use strict";
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
Math.__name__ = "Math";
var Std = function() { };
Std.__name__ = "Std";
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
var haxe_Exception = function(message,previous,native) {
	Error.call(this,message);
	this.message = message;
	this.__previousException = previous;
	this.__nativeException = native != null ? native : this;
};
haxe_Exception.__name__ = "haxe.Exception";
haxe_Exception.thrown = function(value) {
	if(((value) instanceof haxe_Exception)) {
		return value.get_native();
	} else if(((value) instanceof Error)) {
		return value;
	} else {
		var e = new haxe_ValueException(value);
		return e;
	}
};
haxe_Exception.__super__ = Error;
haxe_Exception.prototype = $extend(Error.prototype,{
	get_native: function() {
		return this.__nativeException;
	}
	,__class__: haxe_Exception
});
var haxe_ValueException = function(value,previous,native) {
	haxe_Exception.call(this,String(value),previous,native);
	this.value = value;
};
haxe_ValueException.__name__ = "haxe.ValueException";
haxe_ValueException.__super__ = haxe_Exception;
haxe_ValueException.prototype = $extend(haxe_Exception.prototype,{
	__class__: haxe_ValueException
});
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.__name__ = "haxe.iterators.ArrayIterator";
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
	,__class__: haxe_iterators_ArrayIterator
};
var js_Boot = function() { };
js_Boot.__name__ = "js.Boot";
js_Boot.getClass = function(o) {
	if(o == null) {
		return null;
	} else if(((o) instanceof Array)) {
		return Array;
	} else {
		var cl = o.__class__;
		if(cl != null) {
			return cl;
		}
		var name = js_Boot.__nativeClassName(o);
		if(name != null) {
			return js_Boot.__resolveNativeClass(name);
		}
		return null;
	}
};
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(((o) instanceof Array)) {
			var str = "[";
			s += "\t";
			var _g = 0;
			var _g1 = o.length;
			while(_g < _g1) {
				var i = _g++;
				str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( _g ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var str = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		var k = null;
		for( k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str.length != 2) {
			str += ", \n";
		}
		str += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str += "\n" + s + "}";
		return str;
	case "string":
		return o;
	default:
		return String(o);
	}
};
js_Boot.__interfLoop = function(cc,cl) {
	if(cc == null) {
		return false;
	}
	if(cc == cl) {
		return true;
	}
	var intf = cc.__interfaces__;
	if(intf != null) {
		var _g = 0;
		var _g1 = intf.length;
		while(_g < _g1) {
			var i = _g++;
			var i1 = intf[i];
			if(i1 == cl || js_Boot.__interfLoop(i1,cl)) {
				return true;
			}
		}
	}
	return js_Boot.__interfLoop(cc.__super__,cl);
};
js_Boot.__instanceof = function(o,cl) {
	if(cl == null) {
		return false;
	}
	switch(cl) {
	case Array:
		return ((o) instanceof Array);
	case Bool:
		return typeof(o) == "boolean";
	case Dynamic:
		return o != null;
	case Float:
		return typeof(o) == "number";
	case Int:
		if(typeof(o) == "number") {
			return ((o | 0) === o);
		} else {
			return false;
		}
		break;
	case String:
		return typeof(o) == "string";
	default:
		if(o != null) {
			if(typeof(cl) == "function") {
				if(js_Boot.__downcastCheck(o,cl)) {
					return true;
				}
			} else if(typeof(cl) == "object" && js_Boot.__isNativeObj(cl)) {
				if(((o) instanceof cl)) {
					return true;
				}
			}
		} else {
			return false;
		}
		if(cl == Class ? o.__name__ != null : false) {
			return true;
		}
		if(cl == Enum ? o.__ename__ != null : false) {
			return true;
		}
		return false;
	}
};
js_Boot.__downcastCheck = function(o,cl) {
	if(!((o) instanceof cl)) {
		if(cl.__isInterface__) {
			return js_Boot.__interfLoop(js_Boot.getClass(o),cl);
		} else {
			return false;
		}
	} else {
		return true;
	}
};
js_Boot.__cast = function(o,t) {
	if(o == null || js_Boot.__instanceof(o,t)) {
		return o;
	} else {
		throw haxe_Exception.thrown("Cannot cast " + Std.string(o) + " to " + Std.string(t));
	}
};
js_Boot.__nativeClassName = function(o) {
	var name = js_Boot.__toStr.call(o).slice(8,-1);
	if(name == "Object" || name == "Function" || name == "Math" || name == "JSON") {
		return null;
	}
	return name;
};
js_Boot.__isNativeObj = function(o) {
	return js_Boot.__nativeClassName(o) != null;
};
js_Boot.__resolveNativeClass = function(name) {
	return $global[name];
};
var mortonHx_Test = function() { };
mortonHx_Test.__name__ = "mortonHx.Test";
mortonHx_Test.main = function() {
	console.log("src/mortonHx/Test.hx:9:","testing MortonHx");
	var canvas = window.document.createElement("canvas");
	canvas.width = 800;
	canvas.height = 600;
	var ctx = canvas.getContext("2d",null);
	window.document.body.appendChild(canvas);
	mortonHx_Test.drawGrid(ctx,canvas.width,canvas.height,40);
	mortonHx_Test.drawMordon(ctx,canvas.width,canvas.height,40);
};
mortonHx_Test.drawMordon = function(ctx,width,height,step) {
	var wid = Math.ceil(width / 40);
	var hi = Math.ceil(height / 40);
	ctx.beginPath();
	ctx.strokeStyle = "#FF0000";
	var this1 = js_Boot.__cast(0 , Int);
	var j = this1;
	j &= 1431655765;
	j = (j ^ j >> 1) & 858993459;
	j = (j ^ j >> 2) & 252645135;
	j = (j ^ j >> 4) & 16711935;
	j = (j ^ j >> 8) & 65535;
	var j1 = this1 >> 1;
	j1 &= 1431655765;
	j1 = (j1 ^ j1 >> 1) & 858993459;
	j1 = (j1 ^ j1 >> 2) & 252645135;
	j1 = (j1 ^ j1 >> 4) & 16711935;
	j1 = (j1 ^ j1 >> 8) & 65535;
	var p_x = j;
	var p_y = j1;
	ctx.moveTo(40 * p_x + 2,40 * p_y + 2);
	var tot = wid * hi * 40 | 0;
	var _g = 1;
	var _g1 = tot;
	while(_g < _g1) {
		var i = _g++;
		var this1 = js_Boot.__cast(i , Int);
		var j = this1;
		j &= 1431655765;
		j = (j ^ j >> 1) & 858993459;
		j = (j ^ j >> 2) & 252645135;
		j = (j ^ j >> 4) & 16711935;
		j = (j ^ j >> 8) & 65535;
		var j1 = this1 >> 1;
		j1 &= 1431655765;
		j1 = (j1 ^ j1 >> 1) & 858993459;
		j1 = (j1 ^ j1 >> 2) & 252645135;
		j1 = (j1 ^ j1 >> 4) & 16711935;
		j1 = (j1 ^ j1 >> 8) & 65535;
		var p_x = j;
		var p_y = j1;
		if(p_x < wid && p_y < hi) {
			ctx.lineTo(40 * p_x + 2,40 * p_y + 2);
		}
	}
	ctx.stroke();
};
mortonHx_Test.drawGrid = function(ctx,width,height,step) {
	ctx.beginPath();
	ctx.strokeStyle = "#CCCCCC";
	var x = 0;
	while(x <= width) {
		ctx.moveTo(x,0);
		ctx.lineTo(x,height);
		x += step;
	}
	var y = 0;
	while(y <= height) {
		ctx.moveTo(0,y);
		ctx.lineTo(width,y);
		y += step;
	}
	ctx.stroke();
};
Object.defineProperty(String.prototype,"__class__",{ value : String, enumerable : false, writable : true});
String.__name__ = "String";
Array.__name__ = "Array";
var Int = { };
var Dynamic = { };
var Float = Number;
var Bool = Boolean;
var Class = { };
var Enum = { };
js_Boot.__toStr = ({ }).toString;
mortonHx_Test.main();
})(typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);
